version: '3.8'
services:
  php:
    build: ./
    ports:
      - "9090:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: Qaz123!@#

